[수정] terraform api 수정 및 tf 파일 관리
Terraform-Canvas/back-end pull request #26
Opened 2023-07-25 14:43 UTC by dusdjhyeon

## Description

- [x]  tf 파일 생성 api와 실행 api 합치기
- [x]  asg main.tf 수정
- [x]  보안그룹 tf 폴더 분리하기

## Related Issue

close #20 

## Additional
- 보안 그룹의 유연성 및 재사용성 개선 필요
- 아키텍처 다양성 확장에 따라 리소스 폴더 분리 체계화 필요

2023-07-25 15:42 UTC, Eeap commented on app/services/terraform_service.go
> +		if len(matches) > 0 {
위에 선언 부분이라 합쳐서 한줄로 써도 괜찮을 것 같아여`if matches := re.FindAllString(string(sgFileContent), -1); len(matches) > 0 {}` 요런식으로요!

2023-07-25 15:42 UTC, Eeap commented on platform/terraform/vpc/main.tf
> +    values = ["ap-northeast-2a", "ap-northeast-2c"]
이건 임시로 넣어놓은건가여??

2023-07-27 16:04 UTC, Eeap requested changes

2023-07-27 16:04 UTC, Eeap commented on app/services/terraform_service.go
> +	for idx, sub := range append(subnetList) {
이 부분은 왜 자기 자신을 append에 넣고 바로 반환만 하는건가요 ?.?

2023-07-27 16:04 UTC, Eeap commented on app/services/terraform_service.go
> +var subnetList []map[string]interface{}
그리고 아마 이거 이렇게 전역으로 사용하면 계속 똑같은 variable로 참조될텐데 초기화 해주는 부분이 있나요?

2023-07-27 16:04 UTC, Eeap commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
그리고 이거 key 값 user_data인데요.. ㅠ,ㅠ

2023-07-27 23:39 UTC, dusdjhyeon commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
엥 user-data인데요..?

2023-07-27 23:40 UTC, dusdjhyeon commented on app/services/terraform_service.go
> +var subnetList []map[string]interface{}
Initialize함수에 있어요

2023-07-27 23:44 UTC, dusdjhyeon commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
이건 바꿀게요

2023-07-27 23:52 UTC, dusdjhyeon commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
이건 고칠게요

2023-07-27 23:54 UTC, dusdjhyeon commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
아 테스트를 다른 곳에서 하고 옮겼더니 안 옮긴게 많네요. 답변들 다 다 설정 되어 있던 것들인데,, 다음부터 주의하겠습니다..

2023-07-28 00:11 UTC, dusdjhyeon commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
그리고 수정 하는 김에 alb public subnet 부분도 var처리 할게요

2023-07-28 00:16 UTC, dusdjhyeon commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
더 큰 문제가 생각나서 잠시 draft로,, 그리고 alb subnet 부분도 var로 바꿀게요

2023-07-28 00:59 UTC, Eeap commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
> 더 큰 문제가 생각나서 잠시 draft로,, 그리고 alb subnet 부분도 var로 바꿀게요
무슨 문제인가요 다현c

2023-07-28 01:01 UTC, Eeap commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
근데 서브넷리스트 나만 initial 안보이나 머지.. 그냥 struct로 가시죠...저거 서버 계속 돌아가면 같은 전역 변수 참조해서 계속 거기에 append 될것 같은데🤔

2023-07-28 01:26 UTC, dusdjhyeon commented on app/services/terraform_service.go
> +		if itemData["user-data"] != nil {
흠.. 한 번 더 올렸는데 다시 봐주실래요?! 여전히 문제 된다면 고치겠습니당

2023-07-28 01:35 UTC, Eeap approved these changes

2023-07-28 04:03 UTC, dusdjhyeon commented on app/services/terraform_service.go
> +					variables[name] = toStringSlice(i)
if문으로 azs만 따로 처리하려다가  나중에 list받을 일 또 있을까봐 그냥 for문 안에서 호출했어요

2023-07-28 05:20 UTC, Eeap approved these changes

2023-07-28 05:31 UTC, merged